name: authentication_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.7
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.0
  meta: ^1.16.0

dev_dependencies:
  firebase_auth_platform_interface: ^7.7.3
  firebase_core_platform_interface: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^9.0.0
